[tool.semantic_release]
# Releases
branch = "main"
version_variable = "src/__init__.py:__version__"
version_source = "tag"
# Commit Parsing
commit_parser = "parser_angular_merge.parse_commit_message"
# Commits
commit_version_number = true
commit_subject = "Release v{version}"
# Distributions
upload_to_pypi = false
upload_to_repository = false
upload_to_release = false
remove_dist = false
#build_command = "true"
