name: Cut release
on:
  workflow_dispatch:
jobs:
  cut-release:
    runs-on: ubuntu-latest
    permissions:
#      actions: write
      contents: write
      id-token: write
    steps:
      - name: Restrict branch
        if: github.ref != 'refs/heads/main'
        run: echo "This workflow may only be run from branch [main]"; exit 1
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.0.4
        with:
          github_token: ${{ secrets.PAT }}
          prerelease: false
          push: true
          changelog: true
          vcs_release: true
      - name: Create release branch
        id: create-release-branch
        env:
          VERSION_TAG: ${{ steps.release.outputs.tag }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
        run: |
          #rm -f .git/COMMIT_EDITMSG
          #git config --global user.email "github-actions@github.com"
          #git config --global user.name "github-actions"
          version_short="$(cut -d '.' -f 1,2 <<< "$VERSION_TAG")"
          release_branch="release/$version_short"
          git checkout -b "$release_branch"
          #git commit --allow-empty -m "Deploy $VERSION_TAG to staging"
          git push -u origin HEAD
          echo "release-branch=$release_branch" >> "$GITHUB_OUTPUT"
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          RELEASE_BRANCH: ${{ steps.create-release-branch.outputs.release-branch }}
        run: gh workflow run '__deploy_stg.yaml' --ref "$RELEASE_BRANCH"
#      - name: Trigger deployment
#        uses: actions/github-script@v6
#        env:
#          RELEASE_BRANCH: ${{ steps.create-release-branch.outputs.release-branch }}
#        with:
#          github-token: ${{ secrets.PAT }}
#          script: |
#            const RELEASE_BRANCH = process.env.RELEASE_BRANCH
#            github.rest.actions.createWorkflowDispatch({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              workflow_id: '__deploy_stg.yaml',
#              ref: RELEASE_BRANCH,
#            })
