name: Cut release
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.PAT }}
jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest version
        id: get-version
        run: |
          version="$(git tag -l --sort=version:refname 'v*' | tail -n1)"
          version_short="$(cut -d '.' -f 1,2 <<< "$version")"
          {
            printf "version=%s\n" "$version"
            printf "version-short=%s\n" "$version_short"
          } >> "$GITHUB_OUTPUT"
      - name: Bump main
        uses: python-semantic-release/python-semantic-release@v8.0.4
        with:
          root_options: "-v --noop"
          force: minor
          prerelease: true
          vcs_release: false
      - name: Create release branch
        env:
          RELEASE_BRANCH: release/${{ steps.get-version.outputs.version-short }}
        run: |
          git checkout -b "$RELEASE_BRANCH"
          #git push -u origin HEAD
      - name: Bump release branch
        uses: python-semantic-release/python-semantic-release@v8.0.4
        with:
          root_options: "-v --noop"
          force: minor
          prerelease: true
          vcs_release: false
