name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: A valid version tag to deploy.
  push:
    branches:
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release_action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout version
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version_tag }}