name: Release

on:
  push:
    branches:
      - release/*
    paths-ignore:
      - CHANGELOG.md
      - src/__init__.py

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    uses: manudawber/python-semantic-release/.github/workflows/semantic_release.yaml@main
    permissions:
      contents: write
    with:
      github_actions_repo_ref: main
      version_options: --prerelease --no-vcs-release
    secrets:
      release_token: ${{ secrets.PAT }}
