name: Deploy to Staging

on:
  push:
    branches:
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release_action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo Hello world