name: Release

on:
  push:
    branches:
      - ignore
    paths-ignore:
      - CHANGELOG.md
      - src/__init__.py

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release_action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Bump main
#        uses: python-semantic-release/python-semantic-release@v8.0.4
#        with:
#          github_token: ${{ secrets.PAT }}
#          prerelease: true
#          commit: false
#          changelog: true
#          push: true
#          vcs_release: false
#  release:
#    name: Release
#    uses: manudawber/python-semantic-release/.github/workflows/semantic_release.yaml@main
#    permissions:
#      contents: write
#    with:
#      github_actions_repo_ref: main
#      version_options: --no-vcs-release
#    secrets:
#      release_token: ${{ secrets.PAT }}
