name: Cherry pick
on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: A commit ID to cherry pick to a release branch.
        required: true
env:
  INPUT_COMMIT_ID: ${{ inputs.commit_id }}
jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Validate branch
        if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/release/') != true
        run: echo "This workflow may only be run from release branches [release/**]"; exit 1
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate commit
        run: |
          commit_message="$(git log --format=%s%b -n 1 "$INPUT_COMMIT_ID")"
          commit_type="${commit_message%%:*}"
          if [[ "$commit_type" != 'fix' ]]; then
            echo "Only commits of the type [fix] can be cherry picked to a release branch"
            exit 1
          fi
      - name: Cherry pick commit
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git cherry-pick "$INPUT_COMMIT_ID"
          git push -u origin
      - name: Release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.0.4
        with:
          github_token: ${{ secrets.PAT }}
          force: patch
      - name: Trigger staging deployment
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          VERSION: ${{ steps.release.outputs.tag }}
        run: gh workflow run '__deploy_stg.yaml' --ref "$GITHUB_REF" -f version="$VERSION"
