name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install python-semantic-release
      - env:
          PYTHONPATH: ${{ github.workspace }}/src
          GH_TOKEN: ${{ secrets.PAT }}
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          semantic-release publish \
            -v DEBUG
            -D commit_author="$GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>"

#      - name: Python Semantic Release
#        uses: relekang/python-semantic-release@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
