name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  pull-requests: read

jobs:
  validate-title:
    name: Validate title
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
